version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '127.0.0.1:5436:5432'
    environment:
      POSTGRES_USER: scouti
      POSTGRES_PASSWORD: scouti1
      POSTGRES_DB: scoutidb
      DEBUG_SQL: 'true'
