export enum ErrorCode {
  NOT_FOUND = 'NOT_FOUND',
  FORBIDDEN = 'FORBIDDEN',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  INVITE_RESPONDENT_ERROR = 'INVITE_RESPONDENT_ERROR',
  START_SESSION_ERROR = 'START_SESSION_ERROR',
} 