name: Deploy Backend to Dev ENV

on:
  workflow_dispatch:

# on:
#   push:
#     branches:
#       - main

#     paths:
#       - 'backend/**'

jobs:
  deploy-backend:
    name: Deploy Backend
    uses: ./.github/workflows/workflow_deploy_be.yml
    with:
      environment: 'dev'
      aws_region: 'us-east-1'
      infra_dir: 'infra/terraform/environments/dev'
      node_app_dir: 'backend'
      cluster_name: 'okemilli-dev-cluster'
      service_name: 'okemilli-dev-service'
      tag_name: 'latest'

    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
      ECR_URL: '038462754274.dkr.ecr.us-east-1.amazonaws.com/okmillie-dev-ecr'
